library(dplyr)
library(feather)
library(leaflet)
library(shiny)
library(dygraphs)
library(xts)
library(geosphere)
library(DT)
library(htmltools)
library(rgeos)
library(sf)
library(fasterize)
library(raster)
library(spData)
library(ggmap)
library(shinydashboard)
library(dashboardthemes)
library(shinybusy)

# read data
data <- feather::read_feather('ships.feather')
#data <- data %>%dplyr::filter(is_parked == 0 )
source('functions.R')